[build]
  command = "npm run build"
  publish = "dist"

# Handle widget routes
[[redirects]]
  from = "/counter"
  to = "/counter/index.html"
  status = 200

[[redirects]]
  from = "/message"
  to = "/message/index.html"
  status = 200

# Handle direct access to widget paths
[[redirects]]
  from = "/counter/*"
  to = "/counter/index.html"
  status = 200

[[redirects]]
  from = "/message/*"
  to = "/message/index.html"
  status = 200

# Fallback redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200